### ISSUE TITLE
How To Install Windows Component?

### ISSUE THREAD

**Issue by autolog** [Ghawken/IndigoPluginCommunicator#1]
This looks really interesting :)

Working on the basis of even sooner as per "Coming soon.....or even sooner depending on interest", I downloaded the plugin and windows communicator. Whilst I have the plugin installed in Indigo, I can't quite fathom out how to install the Windows Component on my Win10 Blue Iris VM.

Of course I could be too far ahead of the curve. ;)

**Comment by Ghawken** [comment]
Far too ahead!
I need to package up separate 32bit and 64bit installers.

But making so many changes if I add something new at PC end, breaks Indigo end.  So didn't really want to release until mostly bedded down.  As installing both Indigoserver and PC end again is a pain (particularly on my 6-7 installs)

Also been a request to change the icon, and changing some cosmetic aspects, and testing the idletime - which is working but giving me some odd'ish results in VMs.  W

Give me a bit and will link to installer for Beta testing.

**Comment by autolog** [comment]
I thought that might be the case. :)
It is 23:20 here in the Uk - So pick it up tomorrow or when available.
Looks to be a really interesting plugin. :)
